### ISSUE TITLE
Bill of Meterials BOM / PCBway & JLC Compatiable Gerbers

### ISSUE THREAD

**Issue by harrypm** [Stefan-Olt/MISRC#2]
# To Do

- [x] Bill of Materials
- [x] PCBway Gerbers
- [x] JLCPCB Gerbers 

## Notes 

Drill Files and solder mask layers.

**Comment by Stefan-Olt** [comment]
Gerbers and BOM is added, it needs to be checked what is still required for automated assembly

**Comment by dellsam34** [comment]
When this will be available?

**Comment by harrypm** [comment]
@dellsam34 It already is available, if you mean when will 1-click ordering of the PCB fabricated will be available, then well that will be after Chinese newyears as all the fabs are closed currently, and the tedious BOM price adjustments are not finished, due to minimum order quantities of items like the DIP switches.

**Comment by dellsam34** [comment]
Will the order include a fully assembled unit or the buyer has to tackle the manufacturing process?

**Comment by harrypm** [comment]
Fully assembled main PCB, all you will have to do is just cut two pins and push on the fx3 USB board, firmware is loaded in live which makes everything very software side fire and forget configurable, but a second revision may have it all just integrated into a single PCB, a piping play device with a GUI software later down the line etc 

There will be an announcement when it's available and setup docs are completely finished for end users, it's essentially the same procedure as a Domesday Duplicator but without the manually flashing 2 boards part very friendly to anyone that can read a single page guide.

That will also be a guide for manually soldering as it will still most likely be cheaper just to buy your own BNC connectors and solder than paying a fab to source the parts which considering the price of the tooling currently it's not an unreasonable thing for most people to do for THT parts 10 seconds of effort.
